[package]
name = "grammarsmith"
version = "0.1.0"
edition = "2021"

[features]
serde = ["dep:serde"]

[dependencies]
serde = { version = "1.0", optional = true, features = ["derive"] }
proptest = "1.6.0"
